export const EXCEL_SERVICE_CATEGORIES = {
  GENERAL: 'General',
  SOCIAL: 'Social',
  ECONOMIC: 'Economic',
  ENVIRONMENTAL: 'Environmental',
} as const

export type ExcelServiceCategory = typeof EXCEL_SERVICE_CATEGORIES[keyof typeof EXCEL_SERVICE_CATEGORIES]

export const EXCEL_SERVICE_CATEGORY_LIST: ExcelServiceCategory[] = [
  EXCEL_SERVICE_CATEGORIES.GENERAL,
  EXCEL_SERVICE_CATEGORIES.SOCIAL,
  EXCEL_SERVICE_CATEGORIES.ECONOMIC,
  EXCEL_SERVICE_CATEGORIES.ENVIRONMENTAL,
]
